version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notatnik
    volumes: ["db_data:/var/lib/postgresql/data"]

  backend:
    build: ./backend
    ports:
    - "8000:8000"

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/notatnik
    depends_on: [db]
    restart: always

  frontend:
    build: ./frontend
    ports: ["80:80"]
    depends_on: [backend]
    restart: always


volumes:
  db_data:
